github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-maintainers"

package:
  repositories:   ["docker.io/paketobuildpacks/graalvm","gcr.io/paketo-buildpacks/graalvm"]
  register:       true
  registry_token: ${ secrets.PAKETO_BOT_GITHUB_TOKEN }

docker_credentials:
- registry: gcr.io
  username: _json_key
  password: ${{ secrets.GCR_PUSH_BOT_JSON_KEY }}
- registry: docker.io
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- name:            JDK 11
  id:              jdk
  version_pattern: "11\\.[\\d]+\\.[\\d]+"
  purl_pattern:    "11\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/graalvm-dependency:main
  with:
    glob:    graalvm-ce-java11-linux-amd64-.+.tar.gz
    token:   ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    version: 11
- name:            Native Image 11
  id:              native-image-svm
  version_pattern: "11\\.[\\d]+\\.[\\d]+"
  cpe_pattern:     "[\\d]+\\.[\\d]+\\.[\\d]+\\.?[\\d]?"
  purl_pattern:    "[\\d]+\\.[\\d]+\\.[\\d]+\\.?[\\d]?"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/graalvm-dependency:main
  with:
    glob:    native-image-installable-svm-java11-linux-amd64-.+.jar
    token:   ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    version: 11
- name:            JDK 17
  id:              jdk
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  purl_pattern:    "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/graalvm-dependency:main
  with:
    glob:    graalvm-ce-java17-linux-amd64-.+.tar.gz
    token:   ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    version: 17
- name:            Native Image 17
  id:              native-image-svm
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  cpe_pattern:     "[\\d]+\\.[\\d]+\\.[\\d]+\\.?[\\d]?"
  purl_pattern:    "[\\d]+\\.[\\d]+\\.[\\d]+\\.?[\\d]?"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/graalvm-dependency:main
  with:
    glob:    native-image-installable-svm-java17-linux-amd64-.+.jar
    token:   ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    version: 17
- name:            JDK 19
  id:              jdk
  version_pattern: "19\\.[\\d]+\\.[\\d]+"
  purl_pattern:    "19\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/graalvm-dependency:main
  with:
    glob:    graalvm-ce-java19-linux-amd64-.+.tar.gz
    token:   ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    version: 19
- name:            Native Image 19
  id:              native-image-svm
  version_pattern: "19\\.[\\d]+\\.[\\d]+"
  cpe_pattern:     "[\\d]+\\.[\\d]+\\.[\\d]+\\.?[\\d]?"
  purl_pattern:    "[\\d]+\\.[\\d]+\\.[\\d]+\\.?[\\d]?"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/graalvm-dependency:main
  with:
    glob:    native-image-installable-svm-java19-linux-amd64-.+.jar
    token:   ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    version: 19
