github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.JAVA_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-buildpacks"

package:
  repository:     gcr.io/paketo-buildpacks/graalvm
  register:       true
  registry_token: ${{ secrets.JAVA_GITHUB_TOKEN }}

docker_credentials:
- registry: gcr.io
  username: _json_key
  password: ${{ secrets.JAVA_GCLOUD_SERVICE_ACCOUNT_KEY }}

dependencies:
- name:            JDK 8
  id:              jdk
  version_pattern: "8\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/graalvm-dependency:main
  with:
    glob:    graalvm-ce-java8-linux-amd64-.+.tar.gz
    token:   ${{ secrets.JAVA_GITHUB_TOKEN }}
    version: 8
- name:            Native Image 8
  id:              native-image-svm
  version_pattern: "8\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/graalvm-dependency:main
  with:
    glob:    native-image-installable-svm-java8-linux-amd64-.+.jar
    token:   ${{ secrets.JAVA_GITHUB_TOKEN }}
    version: 8
- name:            JDK 11
  id:              jdk
  version_pattern: "11\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/graalvm-dependency:main
  with:
    glob:    graalvm-ce-java11-linux-amd64-.+.tar.gz
    token:   ${{ secrets.JAVA_GITHUB_TOKEN }}
    version: 11
- name:            Native Image 11
  id:              native-image-svm
  version_pattern: "11\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/graalvm-dependency:main
  with:
    glob:    native-image-installable-svm-java11-linux-amd64-.+.jar
    token:   ${{ secrets.JAVA_GITHUB_TOKEN }}
    version: 11
- name:            JDK 17
  id:              jdk
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/graalvm-dependency:main
  with:
    glob:    graalvm-ce-java17-linux-amd64-.+.tar.gz
    token:   ${{ secrets.JAVA_GITHUB_TOKEN }}
    version: 17
- name:            Native Image 17
  id:              native-image-svm
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/graalvm-dependency:main
  with:
    glob:    native-image-installable-svm-java17-linux-amd64-.+.jar
    token:   ${{ secrets.JAVA_GITHUB_TOKEN }}
    version: 17
