github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-maintainers"

package:
  repositories:   ["docker.io/paketobuildpacks/graalvm","gcr.io/paketo-buildpacks/graalvm"]
  register:       true
  registry_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

docker_credentials:
- registry: gcr.io
  username: _json_key
  password: ${{ secrets.GCR_PUSH_BOT_JSON_KEY }}
- registry: docker.io
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- name:            JDK 17
  id:              jdk
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  purl_pattern:    "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       graalvm-community-jdk-.*_linux-x64_bin.tar.gz
    owner:      graalvm
    repository: graalvm-ce-builds
    tag_filter: "^jdk-(17\\.[\\d]+\\.[\\d])$"
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    version:    17
- name:            JDK 20
  id:              jdk
  version_pattern: "20\\.[\\d]+\\.[\\d]+"
  purl_pattern:    "20\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/graalvm-dependency:main
  with:
    glob:       graalvm-community-jdk-.*_linux-x64_bin.tar.gz
    owner:      graalvm
    repository: graalvm-ce-builds
    tag_filter: "^jdk-(20\\.[\\d]+\\.[\\d])$"
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    version:    20