# Copyright 2018-2020 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.6"

[buildpack]
id       = "paketo-buildpacks/graalvm"
name     = "Paketo GraalVM Buildpack"
version  = "{{.version}}"
homepage = "https://github.com/paketo-buildpacks/graalvm"
description = "A Cloud Native Buildpack that provides the GraalVM implementations of JREs, JDKs and Native Image tools"
keywords    = ["java", "jvm", "jre", "jdk", "native-image"]

[[buildpack.licenses]]
type = "Apache-2.0"
uri  = "https://github.com/paketo-buildpacks/graalvm/blob/main/LICENSE"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "io.paketo.stacks.tiny"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[metadata.configurations]]
name        = "BPL_JVM_HEAD_ROOM"
description = "the headroom in memory calculation"
default     = "0"
launch      = true

[[metadata.configurations]]
name        = "BPL_JVM_LOADED_CLASS_COUNT"
description = "the number of loaded classes in memory calculation"
default     = "35% of classes"
launch      = true

[[metadata.configurations]]
name        = "BPL_JVM_THREAD_COUNT"
description = "the number of threads in memory calculation"
default     = "250"
launch      = true

[[metadata.configurations]]
name        = "BP_JVM_VERSION"
description = "the Java version"
default     = "11"
build       = true

[[metadata.configurations]]
name        = "JAVA_TOOL_OPTIONS"
description = "the JVM launch flags"
launch      = true

[[metadata.dependencies]]
id      = "jdk"
name    = "GraalVM JDK"
version = "8.0.302"
uri     = "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.2.0/graalvm-ce-java8-linux-amd64-21.2.0.tar.gz"
sha256  = "0ea16ff2fe178800195e2918ee7ceee352601d4161a17eac67979febaaecfe05"
stacks  = [ "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "native-image-svm"
name    = "GraalVM Native Image Substrate VM"
version = "8.0.302"
uri     = "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.2.0/native-image-installable-svm-java8-linux-amd64-21.2.0.jar"
sha256  = "4c434b1043a3aeb3307296b66fe040b6d53a93a8090ea2e298b4ea455bcf9bca"
stacks  = [ "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jdk"
name    = "GraalVM JDK"
version = "11.0.12"
uri     = "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.2.0/graalvm-ce-java11-linux-amd64-21.2.0.tar.gz"
sha256  = "bbd3e03025168172a76c2a29e6a14c1c37e3476b30774259c3ef5952fb86f470"
stacks  = [ "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "native-image-svm"
name    = "GraalVM Native Image Substrate VM"
version = "11.0.12"
uri     = "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.2.0/native-image-installable-svm-java11-linux-amd64-21.2.0.jar"
sha256  = "6fc4c6becbe0331aa0a038660fde7c4769c6d6e97d5a90a716a898188d3a6df9"
stacks  = [ "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jdk"
name    = "GraalVM JDK"
version = "16.0.0"
uri     = "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.2.0/graalvm-ce-java16-linux-amd64-21.2.0.tar.gz"
sha256  = "none"
stacks  = [ "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "native-image-svm"
name    = "GraalVM Native Image Substrate VM"
version = "16.0.0"
uri     = "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.2.0/native-image-installable-svm-java16-linux-amd64-21.2.0.jar"
sha256  = "none"
stacks  = [ "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jvmkill"
name    = "JVMKill Agent"
version = "1.16.0"
uri     = "https://github.com/cloudfoundry/jvmkill/releases/download/v1.16.0.RELEASE/jvmkill-1.16.0-RELEASE.so"
sha256  = "a3092627b082cb3cdbbe4b255d35687126aa604e6b613dcda33be9f7e1277162"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/jvmkill/blob/main/LICENSE"

[metadata]
pre-package   = "scripts/build.sh"
include-files = [
  "LICENSE",
  "NOTICE",
  "README.md",
  "bin/build",
  "bin/detect",
  "bin/helper",
  "bin/main",
  "buildpack.toml",
]
